---
title: "Hello R"
author: "Jodelle Joseph"
date: "Data 2401"
output: html_document
---

MAKE SURE YOU READ AND FOLLOW **ALL** INSTRUCTIONS ON THE INSTRUCTION DOCUMENT. 

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1
the datasaurus_dozen has 1846 rows and 2 columns.The variables included are x and y values

### Exercise 2
## Now to plot the dino set

```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```


```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

## Plots for star dataset

```{r plot-star}
star_data <- datasaurus_dozen %>%
filter(dataset == "star") 
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

Correlation for star data set
```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))
```

### Exercise 4
## Now to plot the circle dataset
 
```{r plot-circle}
circle_data <- datasaurus_dozen %>%
filter(dataset == "circle") 
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()

```

```{r cor-circle}
circle_data %>%
  summarize(r = cor (x,y))

```

### Exercise 5
## Plotting all the datasets

```{r plot-*}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
 geom_point()+
 facet_wrap(~ dataset, ncol = 3) + # facet the dataset variable, in 3 cols 
 theme(legend.position = "none") 

datasaurus_dozen %>%
 group_by(dataset) %>% 
 summarize(r = cor(x, y)) %>% 
 print(13)

## `summarize()` ungrouping output (override with `.groups` argument)
## # A tibble: 13 x 2
## dataset r
##
## 1 away -0.0641
## 2 bullseye -0.0686
## 3 circle -0.0683
## 4 dino -0.0645
## 5 dots -0.0603
## 6 h_lines -0.0617 
## 7 high_lines -0.0685
## 8 slant_down -0.0690
## 9 slant_up -0.0686
## 10 star -0.0630
## 11 v_lines -0.0694
## 12 wide_lines -0.0666
## 13 x_shape -0.0656 
```